services: 
    Seq:
        image: datalust/seq:latest
        container_name: Seq
        restart: always
        ports:
            - 5341:80
        environment:
            ACCEPT_EULA: Y
            SEQ_LICENSE: trial
        volumes:
            - .container/seq:/data
    MsSql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: MsSql
        restart: unless-stopped
        volumes:
        - .container/mssql:/var/opt/mssql/data
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=SupperStrongPassword123321!
        ports:
        - 1433:1433